# Generated by Django 5.0.5 on 2024-05-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="descripition",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="descripition",
            new_name="description",
        ),
    ]
