# Generated by Django 5.0.5 on 2024-05-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_descripition_category_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
